// <auto-generated />
using System;
using InspectorPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InspectorPortal.Data.Migrations
{
    [DbContext(typeof(InspectorPortalDbContext))]
    [Migration("20230322165418_newDatas")]
    partial class newDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InspectorPortal.Data.Entities.DisiplinCezasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaskanlikOneri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisiplinKuruluOneri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<string>("MufettisOneri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Onaylanan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevID");

                    b.ToTable("DisiplinCezalari");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<int>("GorevTipi")
                        .HasColumnType("int");

                    b.Property<decimal?>("KamuZarari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Konusu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerilisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnitID");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.HukukiIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaskanlikOneri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<string>("MufettisOneri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Onaylanan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevID");

                    b.ToTable("HukukiIslemler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.IdariTedbir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaskanlikOneri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<string>("MufettisOneri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Onaylanan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevID");

                    b.ToTable("IdariTedbirler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Inceleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevID");

                    b.ToTable("Incelemeler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Mufettis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BabaAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CalismaDurumu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DogumYeri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("IseBaslama")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("KurumSicilNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedeniHal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MezunOkul")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MufettisNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unvan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Mufettisler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.MufettisGorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<int>("MufettisID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevID");

                    b.HasIndex("MufettisID");

                    b.ToTable("MufettisGorevleri");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.PeriyodikTeftis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<string>("TeftisDonemi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UniteBirimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevID");

                    b.HasIndex("UniteBirimId");

                    b.ToTable("PeriyodikTeftisler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("İsim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Sorusturma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevID")
                        .HasColumnType("int");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevID");

                    b.HasIndex("PersonelID");

                    b.ToTable("Sorusturmalar");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.UniteBirimDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BirimID")
                        .HasColumnType("int");

                    b.Property<string>("BirimSorumlusu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BirimID");

                    b.ToTable("UniteBirimler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.DisiplinCezasi", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.Gorev", "Gorev")
                        .WithMany("DisiplinCezalari")
                        .HasForeignKey("GorevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Gorev", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.UniteBirimDto", "UniteBirimDto")
                        .WithMany()
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniteBirimDto");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.HukukiIslem", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.Gorev", "Gorev")
                        .WithMany("HukukiIslemler")
                        .HasForeignKey("GorevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.IdariTedbir", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.Gorev", "Gorev")
                        .WithMany("IdariTedbirler")
                        .HasForeignKey("GorevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Inceleme", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.MufettisGorev", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspectorPortal.Data.Entities.Mufettis", "Mufettis")
                        .WithMany()
                        .HasForeignKey("MufettisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Mufettis");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.PeriyodikTeftis", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspectorPortal.Data.Entities.UniteBirimDto", null)
                        .WithMany("PeriyodikTeftisler")
                        .HasForeignKey("UniteBirimId");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Sorusturma", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspectorPortal.Data.Entities.Personel", "SorumluPersonel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("SorumluPersonel");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.UniteBirimDto", b =>
                {
                    b.HasOne("InspectorPortal.Data.Entities.UniteBirimDto", "UstBirim")
                        .WithMany()
                        .HasForeignKey("BirimID");

                    b.Navigation("UstBirim");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.Gorev", b =>
                {
                    b.Navigation("DisiplinCezalari");

                    b.Navigation("HukukiIslemler");

                    b.Navigation("IdariTedbirler");
                });

            modelBuilder.Entity("InspectorPortal.Data.Entities.UniteBirimDto", b =>
                {
                    b.Navigation("PeriyodikTeftisler");
                });
#pragma warning restore 612, 618
        }
    }
}
